"""Backwards-compat shim. Original location was scripts/a1_context_source_ablation.py.

Re-exports everything (including private underscore-prefixed names)
from the new location: experiments.e03_same_target_ablation.run_a1_context_source.

Generated by Phase 5 of the migration. Once all callers are migrated
to the new path, this file can be deleted.
"""
from experiments.e03_same_target_ablation.run_a1_context_source import *  # noqa: F401,F403
# Module-level re-export to also surface underscore-prefixed names
# that the wildcard import would skip.
import experiments.e03_same_target_ablation.run_a1_context_source as _src
_globals = globals()
for _name in dir(_src):
    if _name.startswith("__") and _name.endswith("__"):
        continue
    _globals[_name] = getattr(_src, _name)
del _name, _src, _globals
