"""Backwards-compat shim. Original location was scripts/run_downstream_clean_control.py.

Re-exports everything (including private underscore-prefixed names)
from the new location: experiments.e07_downstream_pilot.run_clean_control.

Generated by Phase 5 of the migration. Once all callers are migrated
to the new path, this file can be deleted.
"""
from experiments.e07_downstream_pilot.run_clean_control import *  # noqa: F401,F403
# Module-level re-export to also surface underscore-prefixed names
# that the wildcard import would skip.
import experiments.e07_downstream_pilot.run_clean_control as _src
_globals = globals()
for _name in dir(_src):
    if _name.startswith("__") and _name.endswith("__"):
        continue
    _globals[_name] = getattr(_src, _name)
del _name, _src, _globals
